services:
  rehMEDErrorApp:
    image: sgukz/react-app-mederror:1.22.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3016}:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
