services:
  rehAPIMedError:
    image: sgukz/api-med-error-prod:1.11.5
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT-8003}:${PORT-8003}"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
        mode: "non-blocking"
        max-buffer-size: "4m"
networks:
  default:
    name: api-shared-net
    external: true
